apiVersion: v1
kind: Secret
metadata:
  name: diaryapp-secrets
  namespace: diaryapp
type: Opaque
stringData:
  SA_PASSWORD: "MySecure#Pass2024!"
  ConnectionStrings__DefaultConnection: "Server=sqlserver-service;Database=DiaryAppDb;User Id=sa;Password=MySecure#Pass2024!;TrustServerCertificate=True;"
  ConnectionStrings__defaultConnection: "Server=sqlserver-service;Database=DiaryAppDb;User Id=sa;Password=MySecure#Pass2024!;TrustServerCertificate=True;"